PV_CONFIG:
  IMAGE_PV_NAME: 'INJ-BI:PRF01:CCD_IMAGE'
  RESULT_PV_NAME: 'INJ-BI:PRF01:CCD_SEG_IMAGE'
  IMAGE_WIDTH: 1280
  IMAGE_HEIGHT: 1024
  YOLO_IMAGE_WIDTH: 1088
  YOLO_IMAGE_HEIGHT: 1088
  # 原始Profile图像PV列表（原始尺寸）
  INJ_PROFILE_IMAGE_PVS: [
    'INJ-BI:PRF01:CCD_IMAGE', 'INJ-BI:PRFB1:CCD_IMAGE',
    'INJ-BI:PRF02:CCD_IMAGE', 'INJ-BI:PRFB2:CCD_IMAGE'
  ]
  COL_PROFILE_IMAGE_PVS: [
    'COL-BI:PRF01:CCD_IMAGE', 'COL-BI:PRF02:CCD_IMAGE', 'COL-BI:PRF03:CCD_IMAGE',
    'COL-BI:PRF04:CCD_IMAGE', 'COL-BI:PRF05:CCD_IMAGE'
  ]
  DIAG0_PROFILE_IMAGE_PVS: [
    'DIAG0-BI:PRF01:CCD_IMAGE', 'DIAG0-BI:PRF02:CCD_IMAGE', 'DIAG0-BI:PRF03:CCD_IMAGE',
    'DIAG0-BI:PRF04:CCD_IMAGE', 'DIAG0-BI:PRF05:CCD_IMAGE', 'DIAG0-BI:PRF06:CCD_IMAGE',
    'DIAG0-BI:PRF07:CCD_IMAGE', 'DIAG0-BI:PRF08:CCD_IMAGE', 'DIAG0-BI:PRFB1:CCD_IMAGE'
  ]
  DIAG1_PROFILE_IMAGE_PVS: [
    'DIAG1-BI:PRF01:CCD_IMAGE', 'DIAG1-BI:PRF02:CCD_IMAGE', 'DIAG1-BI:PRF03:CCD_IMAGE',
    'DIAG1-BI:PRF04:CCD_IMAGE', 'DIAG1-BI:PRF05:CCD_IMAGE', 'DIAG1-BI:PRF06:CCD_IMAGE',
    'DIAG1-BI:PRF07:CCD_IMAGE', 'DIAG1-BI:PRFB1:CCD_IMAGE'
  ]
  # 原始Profile图像PV列表（ROI尺寸）
  INJ_PROFILE_ROI_IMAGE_PVS: [
    'INJ-BI:PRF01:CCD_ROI_IMAGE', 'INJ-BI:PRFB1:CCD_ROI_IMAGE',
    'INJ-BI:PRF02:CCD_ROI_IMAGE', 'INJ-BI:PRFB2:CCD_ROI_IMAGE'
  ]
  COL_PROFILE_ROI_IMAGE_PVS: [
    'COL-BI:PRF01:CCD_ROI_IMAGE', 'COL-BI:PRF02:CCD_ROI_IMAGE', 'COL-BI:PRF03:CCD_ROI_IMAGE',
    'COL-BI:PRF04:CCD_ROI_IMAGE', 'COL-BI:PRF05:CCD_ROI_IMAGE'
  ]
  DIAG0_PROFILE_ROI_IMAGE_PVS: [
    'DIAG0-BI:PRF01:CCD_ROI_IMAGE', 'DIAG0-BI:PRF02:CCD_ROI_IMAGE', 'DIAG0-BI:PRF03:CCD_ROI_IMAGE',
    'DIAG0-BI:PRF04:CCD_ROI_IMAGE', 'DIAG0-BI:PRF05:CCD_ROI_IMAGE', 'DIAG0-BI:PRF06:CCD_ROI_IMAGE',
    'DIAG0-BI:PRF07:CCD_ROI_IMAGE', 'DIAG0-BI:PRF08:CCD_ROI_IMAGE', 'DIAG0-BI:PRFB1:CCD_ROI_IMAGE'
  ]
  DIAG1_PROFILE_ROI_IMAGE_PVS: [
    'DIAG1-BI:PRF01:CCD_ROI_IMAGE', 'DIAG1-BI:PRF02:CCD_ROI_IMAGE', 'DIAG1-BI:PRF03:CCD_ROI_IMAGE',
    'DIAG1-BI:PRF04:CCD_ROI_IMAGE', 'DIAG1-BI:PRF05:CCD_ROI_IMAGE', 'DIAG1-BI:PRF06:CCD_ROI_IMAGE',
    'DIAG1-BI:PRF07:CCD_ROI_IMAGE', 'DIAG1-BI:PRFB1:CCD_ROI_IMAGE'
  ]
  # 处理后Profile图像PV列表（原始尺寸）
  INJ_PROFILE_SEG_IMAGE_PVS: [
    'INJ-BI:PRF01:CCD_SEG_IMAGE', 'INJ-BI:PRFB1:CCD_SEG_IMAGE',
    'INJ-BI:PRF02:CCD_SEG_IMAGE', 'INJ-BI:PRFB2:CCD_SEG_IMAGE'
  ]
  COL_PROFILE_SEG_IMAGE_PVS: [
    'COL-BI:PRF01:CCD_SEG_IMAGE', 'COL-BI:PRF02:CCD_SEG_IMAGE', 'COL-BI:PRF03:CCD_SEG_IMAGE',
    'COL-BI:PRF04:CCD_SEG_IMAGE', 'COL-BI:PRF05:CCD_SEG_IMAGE'
  ]
  DIAG0_PROFILE_SEG_IMAGE_PVS: [
    'DIAG0-BI:PRF01:CCD_SEG_IMAGE', 'DIAG0-BI:PRF02:CCD_SEG_IMAGE', 'DIAG0-BI:PRF03:CCD_SEG_IMAGE',
    'DIAG0-BI:PRF04:CCD_SEG_IMAGE', 'DIAG0-BI:PRF05:CCD_SEG_IMAGE', 'DIAG0-BI:PRF06:CCD_SEG_IMAGE',
    'DIAG0-BI:PRF07:CCD_SEG_IMAGE', 'DIAG0-BI:PRF08:CCD_SEG_IMAGE', 'DIAG0-BI:PRFB1:CCD_SEG_IMAGE'
  ]
  DIAG1_PROFILE_SEG_IMAGE_PVS: [
    'DIAG1-BI:PRF01:CCD_SEG_IMAGE', 'DIAG1-BI:PRF02:CCD_SEG_IMAGE', 'DIAG1-BI:PRF03:CCD_SEG_IMAGE',
    'DIAG1-BI:PRF04:CCD_SEG_IMAGE', 'DIAG1-BI:PRF05:CCD_SEG_IMAGE', 'DIAG1-BI:PRF06:CCD_SEG_IMAGE',
    'DIAG1-BI:PRF07:CCD_SEG_IMAGE', 'DIAG1-BI:PRFB1:CCD_SEG_IMAGE'
  ]
  # 处理后Profile图像PV列表（ROI尺寸）
  INJ_PROFILE_ROI_SEG_IMAGE_PVS: [
    'INJ-BI:PRF01:CCD_SEG_ROI_IMAGE', 'INJ-BI:PRFB1:CCD_SEG_ROI_IMAGE',
    'INJ-BI:PRF02:CCD_SEG_ROI_IMAGE', 'INJ-BI:PRFB2:CCD_SEG_ROI_IMAGE'
  ]
  COL_PROFILE_ROI_SEG_IMAGE_PVS: [
    'COL-BI:PRF01:CCD_SEG_ROI_IMAGE', 'COL-BI:PRF02:CCD_SEG_ROI_IMAGE', 'COL-BI:PRF03:CCD_SEG_ROI_IMAGE',
    'COL-BI:PRF04:CCD_SEG_ROI_IMAGE', 'COL-BI:PRF05:CCD_SEG_ROI_IMAGE'
  ]
  DIAG0_PROFILE_ROI_SEG_IMAGE_PVS: [
    'DIAG0-BI:PRF01:CCD_SEG_ROI_IMAGE', 'DIAG0-BI:PRF02:CCD_SEG_ROI_IMAGE', 'DIAG0-BI:PRF03:CCD_SEG_ROI_IMAGE',
    'DIAG0-BI:PRF04:CCD_SEG_ROI_IMAGE', 'DIAG0-BI:PRF05:CCD_SEG_ROI_IMAGE', 'DIAG0-BI:PRF06:CCD_SEG_ROI_IMAGE',
    'DIAG0-BI:PRF07:CCD_SEG_ROI_IMAGE', 'DIAG0-BI:PRF08:CCD_SEG_ROI_IMAGE', 'DIAG0-BI:PRFB1:CCD_SEG_ROI_IMAGE'
  ]
  DIAG1_PROFILE_ROI_SEG_IMAGE_PVS: [
    'DIAG1-BI:PRF01:CCD_SEG_ROI_IMAGE', 'DIAG1-BI:PRF02:CCD_SEG_ROI_IMAGE', 'DIAG1-BI:PRF03:CCD_SEG_ROI_IMAGE',
    'DIAG1-BI:PRF04:CCD_SEG_ROI_IMAGE', 'DIAG1-BI:PRF05:CCD_SEG_ROI_IMAGE', 'DIAG1-BI:PRF06:CCD_SEG_ROI_IMAGE',
    'DIAG1-BI:PRF07:CCD_SEG_ROI_IMAGE', 'DIAG1-BI:PRFB1:CCD_SEG_ROI_IMAGE'
  ]

ENVIRON_CONFIG:
  EPICS_CA_MAX_ARRAY_BYTES: '20971520'
  CUDA_VISIBLE_DEVICES: '0'
  YOLO_MODEL_PATH: './model/best.pt'

LOGGING_CONFIG:
  LOG_LEVEL: 'INFO'
  VIS_LOG_FILE: '../logging/visualization.log'
  SERVICE_LOG_FILE: '../logging/service.log'